#pragma once

//ESCRITURA DE DATOS EN SIMU (P3D)									
enum GROUP_ID {
	GROUP0,
};
//DEFINICIONES DE MODULOS (VARIABLES)- P3D LECTURA DE DATOS DEL SIMU
enum DATA_DEFINE_ID {
	DEFINITION_P3D,
};
//DEFINICIONES DE REQ (VARIABLES)	 - P3D LECTURA DE DATOS DEL SIMU
enum P3D_DATA_REQUEST_ID {
	REQUEST_P3D,
};
// TIPOS DE REQUEST			(PMDG)		
enum DATA_REQUEST_ID {
	DATA_REQUEST,
	CONTROL_REQUEST,
	AIR_PATH_REQUEST
};